### ISSUE TITLE
валідація

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-34-React-formik-form#1]
https://github.com/BohdanLuts/home-work-lesson-34-React-formik-form/blob/5bb283802543bd4d2bb568ebcc0e4c4f0fe21c4b/src/utils/validate/validationSchemas.js#L42
- для формулювання зрозумілого для користувача повідомлення тут варто вказати другий параметр

**Comment by BohdanLuts** [comment]
Додані повідомлення в обов'язкових полях.
